apiVersion: v1
data:
  {{- toYaml .Values.elastic_config | nindent 2 }}
  # -- Elasticsearch Zen discovery static unicast hosts
  discovery.zen.ping.unicast.hosts: {{ include "master.fullname" . }}-discovery
kind: ConfigMap
metadata:
  annotations:
  labels:
    {{- include "master.labels" . | nindent 4 }}
  name: {{ include "master.fullname" . }}
