apiVersion: v1
data:
  {{- toYaml .Values.elastic_config | nindent 2 }}
  {{- if semverCompare ">=7.0.0" .Values.image.tag }}
  cluster.initial_master_nodes: {{ $replicas := int (toString (.Values.replicaCount)) }}
  {{- $uname := (include "master.fullname" .) }}
    {{- range $i, $e := untilStep 0 $replicas 1 -}}
  {{ $uname }}-{{ $i }},
    {{- end }}
  discovery.seed_hosts: {{ include "master.fullname" . }}-discovery
  {{- else }}
  # -- Elasticsearch Zen discovery static unicast hosts
  discovery.zen.ping.unicast.hosts: {{ include "master.fullname" . }}-discovery
  {{- end }}
kind: ConfigMap
metadata:
  annotations:
  labels:
    {{- include "master.labels" . | nindent 4 }}
  name: {{ include "master.fullname" . }}
