apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    {{- include "master.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.prometheus.enabled }}
    - port: 9114
      targetPort: metrics
      protocol: TCP
      name: metrics
{{ end }}
  selector:
    {{- include "master.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}-discovery
  labels:
    {{- include "master.labels" . | nindent 4 }}
spec:
  clusterIP: None
  {{- if semverCompare ">=7.0.0" .Values.image.tag }}
  publishNotReadyAddresses: true
  {{- end }}
  ports:
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    {{- include "master.selectorLabels" . | nindent 4 }}
