apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "imagepullsecret-patcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "imagepullsecret-patcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "imagepullsecret-patcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: CONFIG_FORCE
              value: {{ .Values.conf.force }}
            - name: CONFIG_DEBUG
              value: "{{ .Values.conf.debug}}"
            - name: CONFIG_MANAGEDONLY
              value: "{{ .Values.conf.managed}}"
            - name: CONFIG_RUNONCE
              value: "{{ .Values.conf.runoce }}"
            - name: CONFIG_SERVICEACCOUNTS
              value: "{{- join "," .Values.conf.service_accounts }}"
            - name: CONFIG_ALLSERVICEACCOUNT
              value: {{ .Values.conf.all_service_accounts}}
            - name: CONFIG_EXCLUDED_NAMESPACES
              value: "{{- join "," .Values.conf.excluded_namespaces }}"
            - name: CONFIG_SECRETNAME
              value: "{{ include "imagepullsecret-patcher.fullname" . }}"
            - name: CONFIG_DOCKERCONFIGJSONPATH
              value: "/app/secrets/.dockerconfigjson"
            - name: CONFIG_LOOP_DURATION
              value: {{ .Values.conf.interval }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: src-dockerconfigjson
              mountPath: "/app/secrets"
              readOnly: true
          resources:
            requests:
              cpu: 0.1
              memory: 15Mi
            limits:
              cpu: 0.2
              memory: 30Mi
      volumes:
        - name: src-dockerconfigjson
          secret: 
            secretName: {{ include "imagepullsecret-patcher.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
