apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devlake.fullname" . }}-env-config
  labels:
    {{- include "devlake.labels" . | nindent 4 }}
data:
  env-cm: |
  {{- range $k, $v := .Values.devlake.dotEnvFile }}
    {{ $k }}={{ $v }}
  {{- end }}