apiVersion: v1
kind: Service
metadata:
  name: {{ include "devlake.fullname" . }}
  labels:
    {{- include "devlake.labels" . | nindent 4 }}
spec:
  type: {{ .Values.devlake.service.type }}
  ports:
    - port: {{ .Values.devlake.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devlake.selectorLabels" . | nindent 4 }}
