apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "data.serviceAccountName" . }}
  labels:
    {{- include "data.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "data.name" . }}


