apiVersion: v1
kind: Service
metadata:
  name: {{ include "data.fullname" . }}
  labels:
    {{- include "data.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
{{- if .Values.prometheus.enabled }}
    - port: 9114
      targetPort: metrics
      protocol: TCP
      name: metrics
{{ end }}
  selector:
    {{- include "data.selectorLabels" . | nindent 4 }}
