name: cerebro
version: 1.0.2
appVersion: 0.9.4
kubeVersion: "<=1.22.0-anything"
apiVersion: v2
description: A Helm chart for Cerebro - a web admin tool that replaces Kopf.
home: https://github.com/lmenezes/cerebro
icon: https://github.com/lmenezes/cerebro/blob/master/public/img/logo.png
sources:
  - https://github.com/lmenezes/cerebro
  - https://github.com/lmenezes/cerebro-docker
maintainers:
  - name: Empathy Platform Team 
    email: ops@empathy.co
