apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cerebro.fullname" . }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
  annotations:
    {{- include "cerebro.annotations" . | nindent 4 }}
data:
  application.conf: |-
    {{- if .Values.config.secret }}
    secret = {{ .Values.config.secret | quote }}
    {{- else }}
    secret = {{ randAlphaNum 64 | quote }}
    {{- end }}

    {{- if .Values.config.tlsVerify }}
    play.ws.ssl.loose.acceptAnyCertificate = false
    {{- else }}
    play.ws.ssl.loose.acceptAnyCertificate = true
    {{- end }}
    {{- if .Values.config.tlsCaCert }}
    play.ws.ssl {
      trustManager = {
        stores = [
          { type = "PEM", path = {{ .Values.config.tlsCaCert | quote }} }
        ]
      }
    }
    {{- end }}

    basePath = {{ .Values.config.basePath | quote }}

    pidfile.path = /dev/null

    rest.history.size = {{ .Values.config.restHistorySize }}

    data.path = "/var/db/cerebro/cerebro.db"

    es = {
      gzip = true
    }

    auth = {
      # either basic or ldap
      type: {{ .Values.env.AUTH_TYPE}}
      settings {
        # LDAP
        url = {{ .Values.env.LDAP_URL }}
        base-dn = {{ .Values.env.LDAP_BASE_DN}}
        method = {{ .Values.env.LDAP_METHOD}}
        user-template = {{ .Values.env.LDAP_USER_TEMPLATE}}
        bind-dn = {{ .Values.env.LDAP_BIND_DN}}
        bind-pw = {{ .Values.env.LDAP_BIND_PWD}}
        group-search {
          base-dn = {{ .Values.env.LDAP_GROUP_BASE_DN}}
          user-attr = {{ .Values.env.LDAP_USER_ATTR}}
          user-attr-template = {{ .Values.env.LDAP_USER_ATTR_TEMPLATE}}
          group = {{ .Values.env.LDAP_GROUP}}
        }

        # Basic auth
        username = {{ .Values.env.BASIC_AUTH_USER}}
        password = {{ .Values.env.BASIC_AUTH_PWD}}
      }
    }

    hosts = [
      {{- range $index, $element := .Values.config.hosts }}
      {{ if $index }},{{ end }}
      {
        host = {{ $element.host | quote }}
        name = {{ $element.name | quote }}
      }
      {{- end }}
    ]
