apiVersion: v1
kind: Service
metadata:
  name: {{ template "cerebro.fullname" . }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- include "cerebro.annotations" . | nindent 4 }}
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cerebro.selectorLabels" . | nindent 6 }}
