apiVersion: v1
kind: Service
metadata:
  name: {{ template "cerebro.fullname" . }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | indent 4 }}
    {{- end }}
  annotations:
    {{- include "cerebro.annotations" . | nindent 4 }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cerebro.selectorLabels" . | nindent 6 }}
