{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cerebro.serviceAccountName" . }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
  annotations:
    {{- include "cerebro.annotations" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
