kind: NetworkPolicy
apiVersion: {{ include "apiVersion" . }}
metadata:
  name: {{ include "networkpolicies.name" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
     {{- include "networkpolicies.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
{{- if .Values.podSelector }}
  podSelector:
    matchLabels:
{{ toYaml .Values.podSelector.matchLabels | indent 7 }}
{{- end }}
{{- if or .Values.ingressRules .Values.egressRules }}
  policyTypes:
{{- if .Values.ingressRules }}
    - Ingress
{{- end }}
{{- if .Values.egressRules }}
    - Egress
{{- end }}
{{- end }}
{{- if .Values.egressRules }}
  egress:
{{-  range $rule := .Values.egressRules }}
    - to:
{{ toYaml $rule.selectors | indent 9 }}
      ports:
{{ toYaml $rule.ports | indent 9 }}  
{{- end }}
{{- end }}
{{- if .Values.ingressRules }}
  ingress:
{{-  range $rule := .Values.ingressRules }}
    - from:
{{ toYaml $rule.selectors | indent 7 }}
      ports:
{{ toYaml $rule.ports | indent 9 }}  
{{- end }}
{{- end }}
--- 
{{- if .Values.dns }}
kind: NetworkPolicy
apiVersion: {{ include "apiVersion" . }}
metadata:
  name: {{ include "networkpolicies.name" . }}-dns
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
     {{- include "networkpolicies.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
{{ toYaml .Values.podSelector.matchLabels | indent 7 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app: {{ .Values.dns.app }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.dns.namespace }}
{{- end }}