apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yace-exporter.fullname" . }}
  labels:
    {{- include "yace-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- tpl .Values.config . | nindent 4 }}
