apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "deadman-switch.fullname" . }}
  labels:
    {{- include "deadman-switch.labels" . | nindent 4 }}
data:
  config.yaml: {{ toYaml .Values.secret | b64enc }}
