apiVersion: v1
kind: Service
metadata:
  name: {{ include "deadman-switch.fullname" . }}
  labels:
    {{- include "deadman-switch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deadman-switch.selectorLabels" . | nindent 4 }}
