{{- if .Values.enabled -}}
apiVersion: v1
data:
  {{- toYaml .Values.global.elastic_config | nindent 2 }}
  {{- toYaml .Values.elastic_config | nindent 2 }}
  {{- if semverCompare ">=7.0.0-0" .Values.image.tag }}
  {{- if .Values.isMaster }}
  cluster.initial_master_nodes: {{ $replicas := int (toString (.Values.replicaCount)) }}
  {{- $uname := .Values.global.masterFullname }}
   {{- range $i, $e := untilStep 0 $replicas 1 -}}
  {{ $uname }}-{{ $i }},
  {{- end }}
  {{- end }}
  discovery.seed_hosts: {{ .Values.global.masterFullname }}-discovery
  {{- else }}
  # -- Elasticsearch Zen discovery static unicast hosts
  discovery.zen.ping.unicast.hosts: {{ .Values.global.masterFullname }}-discovery
  {{- end }}
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
  name: {{ include "statefulset.fullname" . }}
{{- end }}
