{{- if .Values.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "statefulset.serviceAccountName" . }}
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "statefulset.selectorLabels" . | nindent 6 }}
{{- end -}}
