{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "statefulset.fullname" . }}
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.podManagementPolicy }}
  podManagementPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "statefulset.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "statefulset.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "statefulset.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "statefulset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ include "statefulset.fullname" . }}
          env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 5
            exec:
              command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                START_FILE=/tmp/.es_start_file
                http () {
                    local path="$1"
                    curl -XGET -s -k --fail http://127.0.0.1:9200${path}
                }
                if [ -f "${START_FILE}" ]; then
                    echo 'Elasticsearch is already running, lets check the node is healthy and there are statefulset.nodes available'
                    http "/_cluster/health?timeout=0s"
                else
                    echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )'
                    if http "/_cluster/health?wait_for_status=green&timeout=1s" ; then
                        touch ${START_FILE}
                        exit 0
                    else
                        echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
                        exit 1
                    fi
                fi
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{ if .Values.isMaster }}      
        - command:
          - sh
          - -c
          - |
            #!/usr/bin/env bash
            set -eo pipefail
            http () {
                local path="$1"
                if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                  BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                else
                  BASIC_AUTH=''
                fi
                curl -XGET -s -k --fail ${BASIC_AUTH} http://elasticsearch-master:9200${path}
            }
            cleanup () {
              while true ; do
                local master="$(http "/_cat/master?h=node" || echo "")"
                if [[ $master == "elasticsearch-master"* && $master != "${NODE_NAME}" ]]; then
                  echo "This node is not master."
                  break
                fi
                echo "This node is still master, waiting gracefully for it to step down"
                sleep 1
              done
              exit 0
            }
            trap cleanup SIGTERM
            sleep infinity &
            wait $!
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms128m -Xmx128m -Dlog4j2.formatMsgNoLookups=true"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: graceful-termination-handler
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
        {{- end }}
        {{ if .Values.prometheus.enabled }}      
        - command:
          - /bin/elasticsearch_exporter
          - --es.uri=http://127.0.0.1:9200
          image: {{ .Values.prometheus.exporter.image }}
          imagePullPolicy: IfNotPresent
          name: elastic-exporter
          ports:
          - containerPort: 9114
            name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9114
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          securityContext:
            capabilities:
              drop:
              - SETPCAP
              - MKNOD
              - AUDIT_WRITE
              - CHOWN
              - NET_RAW
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - NET_BIND_SERVICE
              - SYS_CHROOT
              - SETFCAP
            readOnlyRootFilesystem: true
        {{- end }}
      initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /data
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: fix-permissions
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /data
            name: data

        - command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: increase-vm-max-map
          securityContext:
            privileged: true
        - command:
          - sysctl
          - -w
          - vm.dirty_ratio=80
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: increase-vm-dirty-ratio
          securityContext:
            privileged: true
        - command:
          - sysctl
          - -w
          - vm.dirty_background_ratio=5
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: increase-vm-dirty-background-ratio
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - ulimit -n 65536
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: increase-fd-ulimit
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - ulimit -l unlimited
          image: {{ .Values.busybox.image }}
          imagePullPolicy: IfNotPresent
          name: increase-fd-unlimited
          securityContext:
            privileged: true
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") .Values.nodeAffinity }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      affinity:
      {{- end }}
      {{- if .Values.affinityOverride }}
        {{- toYaml .Values.affinityOverride | nindent 8 }}
      {{- else }}
      {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - {{ include "statefulset.fullname" . }}
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: {{ .Values.antiAffinityWeight |default 1 }}
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - {{ include "statefulset.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        {{- with .Values.volume.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume.storage }}
        storageClassName: {{ .Values.volume.storage_class }}
{{- end -}}
