{{- if and .Values.keda.enabled -}}
# https://keda.sh/docs/
apiVersion: {{ .Values.keda.apiVersion }}
kind: ScaledObject
metadata:
  name: {{ include "multi-service-deployment.fullname" . }}
  labels:
    {{- include "multi-service-deployment.labels" . | nindent 4 }}
  {{- with .Values.keda.scaledObject.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ include "multi-service-deployment.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  triggers:
{{- with .Values.keda.triggers }}
{{ toYaml . | indent 2 }}
{{ end }}
  advanced:
    restoreToOriginalReplicaCount: {{ .Values.keda.restoreToOriginalReplicaCount }}
{{- if .Values.keda.behavior }}
    horizontalPodAutoscalerConfig:
      behavior:
{{ with .Values.keda.behavior -}}
{{ toYaml . | indent 8 }}
{{ end }}
{{- end }}
{{- end }}