{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
  labels:
    {{- include "multi-service-deployment.labels" $ | nindent 4 }}
  name: {{ include "multi-service-deployment.fullname" $ }}-rule
spec:
  groups:
  - name: {{ include "multi-service-deployment.fullname" $ }}-rule
    rules:
    {{- .Values.prometheusRule.rules | nindent 4 }}
{{ end }}