name: Helm Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!charts/**/README.md'

env:
  HELM_VERSION: "v3.5.3"
  GOMPLATE_VERSION: "v3.9.0"

jobs:
  helm-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Checkout main branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Install Helm"
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: "Install gomplate"
        run: |
          wget -qO gomplate https://github.com/hairyhenderson/gomplate/releases/download/${{ env.GOMPLATE_VERSION }}/gomplate_linux-amd64-slim
          chmod u+x gomplate

      - name: "Run chart-releaser"
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_dir: charts
          charts_repo_url: https://empathyco.github.io/empathy-helm-charts/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Generate README.md from template docs/README.tpl to update list of Charts"
        run: |
          ${{ env.GITHUB_WORKSPACE }}/gomplate -f docs/README.tpl -o ${{ env.GITHUB_WORKSPACE }}/README.md

      - name: "Commit updated README.md to the branch if changed"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Automatic] - Update chart list"
          file_pattern: README.md
