name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          helm template cerebro ./charts/cerebro
          helm install cerebro ./charts/cerebro
          kubectl get pods
