name: Promtool
on:
  pull_request:
    paths:
    - 'charts/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  promtool:
    if: "! github.event.pull_request.head.repo.fork"
    uses: empathyco/platform-reusable-github-actions/.github/workflows/promtool.yml@main
    with:
      path: templates/prometheusrule.yaml
      working-directory: charts/yace-exporter
    secrets:
      GH_TOKEN: ${{ secrets.SUPPORT_TOKEN }}
