apiVersion: v1
kind: Service
metadata:
  name: {{ include "configui.fullname" . }}
  labels:
    {{- include "configui.labels" . | nindent 4 }}
spec:
  type: {{default "ClusterIP" .Values.configui.service.type }}
  ports:
    - port: {{ .Values.configui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "configui.selectorLabels" . | nindent 4 }}
